[".config/bat/themes/TokyoNight.tmTheme"]
type = "file"
refreshPeriod = "1h"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme"

[".local/share/nvim/site/pack/allaman/start/kustomize.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/allaman/kustomize.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/aquasecurity/start/vim-trivy"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/aquasecurity/vim-trivy.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/cappyzawa/start/trim.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/cappyzawa/trim.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/cuducos/start/yaml.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/cuducos/yaml.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/direnv/start/direnv.vim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/direnv/direnv.vim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/echasnovski/start/mini.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/echasnovski/mini.nvim"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/fladson/start/vim-kitty"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/fladson/vim-kitty.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/godlygeek/start/tabular"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/godlygeek/tabular.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/hashivim/start/vim-terraform"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/hashivim/vim-terraform.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/lewis6991/start/gitsigns.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/lewis6991/gitsigns.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/lukas-reineke/start/lsp-format.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/lukas-reineke/lsp-format.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/lukas-reineke/start/virt-column.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/lukas-reineke/virt-column.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/miikanissi/start/modus-themes.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/miikanissi/modus-themes.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/neovim/start/nvim-lspconfig"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/neovim/nvim-lspconfig.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-lua/start/plenary.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-lua/plenary.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-lualine/start/lualine.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-lualine/lualine.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-tree/start/nvim-web-devicons"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-tree/nvim-web-devicons.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-treesitter/nvim-treesitter.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter-textobjects"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/nvimtools/start/none-ls.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvimtools/none-ls.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

{{ if eq .where "home" }}
[".local/share/nvim/site/pack/pearofducks/start/ansible-vim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/pearofducks/ansible-vim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]
{{ end }}

[".local/share/nvim/site/pack/ray-x/start/go.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/ray-x/go.nvim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/rfratto/start/vim.river"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/rfratto/vim-river.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/terrastruct/start/d2-vim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/terrastruct/d2-vim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/tpope/start/vim-endwise"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/tpope/vim-endwise.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/yasuhiroki/start/github-actions-yaml.vim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/yasuhiroki/github-actions-yaml.vim.git"
clone.args = ["--depth=1", "--no-tags"]
pull.args = ["--force"]
