---
.config/bat/themes:
  type: archive
  refreshPeriod: 24h
  url: https://github.com/catppuccin/bat/archive/main.tar.gz
  exact: true
  stripComponents: 2
  include:
    - "*/themes/**"

.config/k9s/skins:
  type: archive
  refreshPeriod: 24h
  url: https://github.com/catppuccin/k9s/archive/main.tar.gz
  exact: true
  stripComponents: 2
  include:
    - "*/dist/**"

.config/nvim/pack/Bekaboo/start/dropbar.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/Bekaboo/dropbar.nvim.git
  pull:
    args:
      - --force

.config/nvim/pack/alker0/start/chezmoi.vim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/alker0/chezmoi.vim.git
  pull:
    args:
      - --force

.config/nvim/pack/cappyzawa/start/trim.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/cappyzawa/trim.nvim.git
  pull:
    args:
      - --force

.config/nvim/pack/catppuccin/start/catppuccin:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/catppuccin/nvim.git
  pull:
    args:
      - --force

.config/nvim/pack/godlygeek/start/tabular:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/godlygeek/tabular.git
  pull:
    args:
      - --force

.config/nvim/pack/mfussenegger/start/nvim-lint:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/mfussenegger/nvim-lint.git
  pull:
    args:
      - --force

.config/nvim/pack/neovim/start/nvim-lspconfig:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/neovim/nvim-lspconfig.git
  pull:
    args:
      - --force

.config/nvim/pack/nvim-lualine/start/lualine.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lualine/lualine.nvim.git
  pull:
    args:
      - --force

.config/nvim/pack/nvim-mini/start/mini.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-mini/mini.nvim.git
  pull:
    args:
      - --force

.config/nvim/pack/nvim-treesitter/start/nvim-treesitter:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-treesitter/nvim-treesitter.git
  pull:
    args:
      - --force

.config/nvim/pack/stevearc/start/conform.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/stevearc/conform.nvim.git
  pull:
    args:
      - --force

.vim/pack/catppuccin/start/catppuccin:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/catppuccin/vim.git
  pull:
    args:
      - --force

.vim/pack/tpope/start/vim-commentary:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/tpope/vim-commentary.git
  pull:
    args:
      - --force
