# yamllint disable rule:line-length
---

.config/nvim/pack/MeanderingProgrammer/start/render-markdown.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/MeanderingProgrammer/render-markdown.nvim.git
  pull.args:
    - --force

.config/nvim/pack/cappyzawa/start/trim.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/cappyzawa/trim.nvim.git
  pull.args:
    - --force

.config/nvim/pack/folke/start/snacks.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/folke/snacks.nvim.git
  pull.args:
    - --force

.config/nvim/pack/kevinhwang91/start/nvim-ufo:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/kevinhwang91/nvim-ufo.git
  pull.args:
    - --force

.config/nvim/pack/kevinhwang91/start/promise-async: # required by nvim-ufo
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/kevinhwang91/promise-async.git
  pull.args:
    - --force

.config/nvim/pack/lewis6991/start/gitsigns.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/lewis6991/gitsigns.nvim.git
  pull.args:
    - --force

# .config/nvim/pack/lukas-reineke/start/virt-column.nvim:
#   type: git-repo
#   refreshPeriod: 1h
#   url: https://github.com/lukas-reineke/virt-column.nvim.git
#   pull.args:
#     - --force

.config/nvim/pack/mfussenegger/start/nvim-lint:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/mfussenegger/nvim-lint.git
  pull.args:
    - --force

.config/nvim/pack/nvim-lua/start/plenary.nvim: # general dependency
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lua/plenary.nvim.git
  pull.args:
    - --force

.config/nvim/pack/nvim-lualine/start/lualine.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lualine/lualine.nvim.git
  pull.args:
    - --force

.config/nvim/pack/nvim-mini/start/mini.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-mini/mini.nvim.git
  pull.args:
    - --force

.config/nvim/pack/nvim-telescope/start/telescope.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-telescope/telescope.nvim.git
  clone.args:
    - --branch=0.1.x
  pull.args:
    - --force

.config/nvim/pack/nvim-treesitter/start/nvim-treesitter:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-treesitter/nvim-treesitter.git
  pull.args:
    - --force

.config/nvim/pack/rebelot/start/kanagawa.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/rebelot/kanagawa.nvim.git
  pull.args:
    - --force

.config/nvim/pack/stevearc/start/conform.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/stevearc/conform.nvim.git
  pull.args:
    - --force
