# [".local/share/nvim/site/pack/allaman/start/kustomize.nvim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/allaman/kustomize.nvim.git"
# pull.args = ["--force"]

# [".local/share/nvim/site/pack/aquasecurity/start/vim-trivy"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/aquasecurity/vim-trivy.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/b0o/start/schemastore.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/b0o/schemastore.nvim.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/cuducos/start/yaml.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/cuducos/yaml.nvim.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/direnv/start/direnv.vim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/direnv/direnv.vim.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/echasnovski/start/mini.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/echasnovski/mini.nvim.git"
clone.args = ["--filter=blob:none"]
pull.args = ["--force"]

[".local/share/nvim/site/pack/fladson/start/vim-kitty"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/fladson/vim-kitty.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/folke/start/tokyonight.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/folke/tokyonight.nvim.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/github/start/copilot.vim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/github/copilot.vim.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/godlygeek/start/tabular"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/godlygeek/tabular.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/hashivim/start/vim-terraform"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/hashivim/vim-terraform.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/ibhagwan/start/fzf-lua"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/ibhagwan/fzf-lua.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/j-hui/start/fidget.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/j-hui/fidget.nvim.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/kdheepak/start/lazygit.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/kdheepak/lazygit.nvim.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/lukas-reineke/start/lsp-format.nvim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/lukas-reineke/lsp-format.nvim.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/lukas-reineke/start/virt-column.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/lukas-reineke/virt-column.nvim.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/mfussenegger/start/nvim-lint"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/mfussenegger/nvim-lint.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/neovim/start/nvim-lspconfig"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/neovim/nvim-lspconfig.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-lua/start/plenary.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-lua/plenary.nvim.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/nvim-telescope/start/nvim-telescope"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/nvim-telescope/telescope.nvim.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/nvim-treesitter/nvim-treesitter.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/nvimtools/start/none-ls.nvim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/nvimtools/none-ls.nvim.git"
# pull.args = ["--force"]

# {{ if eq .where "home" }}
# [".local/share/nvim/site/pack/pearofducks/start/ansible-vim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/pearofducks/ansible-vim.git"
# pull.args = ["--force"]
# {{ end }}

# [".local/share/nvim/site/pack/ray-x/start/go.nvim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/ray-x/go.nvim.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/rfratto/start/vim.river"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/rfratto/vim-river.git"
pull.args = ["--force"]

[".local/share/nvim/site/pack/stevearc/start/confirm.nvim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/stevearc/conform.nvim.git"
pull.args = ["--force"]

# [".local/share/nvim/site/pack/terrastruct/start/d2-vim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/terrastruct/d2-vim.git"
# pull.args = ["--force"]

# [".local/share/nvim/site/pack/williamboman/start/mason.nvim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/williamboman/mason.nvim.git"
# pull.args = ["--force"]

# [".local/share/nvim/site/pack/williamboman/start/mason-lspconfig.nvim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/williamboman/mason-lspconfig.nvim.git"
# pull.args = ["--force"]

# [".local/share/nvim/site/pack/yasuhiroki/start/github-actions-yaml.vim"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/yasuhiroki/github-actions-yaml.vim.git"
# pull.args = ["--force"]

[".local/share/nvim/site/pack/ziglang/start/zig.vim"]
type = "git-repo"
refreshPeriod = "1h"
url = "https://github.com/ziglang/zig.vim.git"
pull.args = ["--force"]
