---
.config/bat/themes/fly16.tmTheme:
  type: file
  refreshPeriod: 24h
  url: https://raw.githubusercontent.com/bluz71/fly16-bat/refs/heads/master/fly16.tmTheme

.config/nvim/pack/bluz71/start/vim-moonfly-colors:
  type: git-repo
  refreshPeriod: 23h
  url: https://github.com/bluz71/vim-moonfly-colors.git
  pull.args:
    - --force

# .config/nvim/pack/direnv/start/direnv.vim:
#   type: git-repo
#   refreshPeriod: 24h
#   url: https://github.com/direnv/direnv.vim.git
#   pull.args:
#     - --force

.config/nvim/pack/echasnovski/start/mini.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/echasnovski/mini.nvim.git
  pull.args:
    - --force

.config/nvim/pack/j-hui/start/fidget.nvim:
  type: git-repo
  refreshPeriod: 23h
  url: https://github.com/j-hui/fidget.nvim.git
  pull.args:
    - --force

.config/nvim/pack/lewis6991/start/gitsigns.nvim:
  type: git-repo
  refreshPeriod: 23h
  url: https://github.com/lewis6991/gitsigns.nvim.git
  pull.args:
    - --force

.config/nvim/pack/lukas-reineke/start/indent-blankline.nvim:
  type: git-repo
  refreshPeriod: 23h
  url: https://github.com/lukas-reineke/indent-blankline.nvim.git
  pull.args:
    - --force

.config/nvim/pack/lukas-reineke/start/virt-column.nvim:
  type: git-repo
  refreshPeriod: 1h
  url: https://github.com/lukas-reineke/virt-column.nvim.git
  pull.args:
    - --force

# .config/nvim/pack/neovim/start/nvim-lspconfig:
#   type: git-repo
#   refreshPeriod: 24h
#   url: https://github.com/neovim/nvim-lspconfig.git
#   pull.args:
#     - --force

.config/nvim/pack/nvim-lua/start/plenary.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lua/plenary.nvim.git
  pull.args:
    - --force

.config/nvim/pack/nvim-lualine/start/lualine.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lualine/lualine.nvim.git
  pull.args:
    - --force

.config/nvim/pack/nvim-telescope/start/telescope.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-telescope/telescope.nvim.git
  clone.args:
    - --branch=0.1.x
  pull.args:
    - --force

.config/nvim/pack/nvim-treesitter/start/nvim-treesitter:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-treesitter/nvim-treesitter.git
  pull.args:
    - --force

.config/nvim/pack/nvim-treesitter/start/nvim-treesitter-textobjects:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-treesitter/nvim-treesitter-textobjects.git
  pull.args:
    - --force

.config/nvim/pack/nvimtools/start/none-ls.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvimtools/none-ls.nvim.git
  pull.args:
    - --force

.config/nvim/pack/nvimtools/start/none-ls-extras.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvimtools/none-ls-extras.nvim.git
  pull.args:
    - --force

.config/nvim/pack/rfratto/start/vim-river:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/rfratto/vim-river.git
  pull.args:
    - --force
