# yamllint disable rule:line-length
---
.local/share/nvim/site/pack/alker0/start/chezmoi.vim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/alker0/chezmoi.vim.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/cappyzawa/start/trim.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/cappyzawa/trim.nvim.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/godlygeek/start/tabular:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/godlygeek/tabular.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/kevinhwang91/start/nvim-ufo:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/kevinhwang91/nvim-ufo.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/kevinhwang91/start/promise-async: # required by nvim-ufo
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/kevinhwang91/promise-async.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/mfussenegger/start/nvim-lint:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/mfussenegger/nvim-lint.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/neovim/start/nvim-lspconfig:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/neovim/nvim-lspconfig.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/nvim-lua/start/plenary.nvim: # general dependency
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lua/plenary.nvim.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/nvim-lualine/start/lualine.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-lualine/lualine.nvim.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/nvim-mini/start/mini.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-mini/mini.nvim.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/nvim-treesitter/nvim-treesitter.git
  clone: &nvim_treesitter_clone
    args:
      - --branch=main
      - --single-branch
  pull:
    args:
      - --force

.local/share/nvim/site/pack/stevearc/start/conform.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/stevearc/conform.nvim.git
  pull:
    args:
      - --force

.local/share/nvim/site/pack/webhooked/start/kanso.nvim:
  type: git-repo
  refreshPeriod: 24h
  url: https://github.com/webhooked/kanso.nvim.git
  pull:
    args:
      - --force
