call_parentheses = "Always"
collapse_simple_statement = "Always"
column_width = 120
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferSingle"

[sort_requires]
enabled = true
