#!/bin/sh

set -o errexit
set -o nounset

case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
  *.md)
    if command -v mdcat >/dev/null; then
      mdcat --local "$1"
      exit 0
    fi
    ;;
esac

exit 1 # leave it to lesspipe.sh
