---@type vim.lsp.Config
return {
    cmd = {
        'harper-ls',
        '--stdio',
    },
    filetypes = {
        'c',
        -- 'clojure',
        'cmake',
        'cpp',
        -- 'cs',
        -- 'dart',
        'gitcommit',
        'go',
        -- 'haskell',
        'html',
        'java',
        'javascript',
        'lua',
        'markdown',
        -- 'nix',
        'php',
        'python',
        'ruby',
        -- 'rust',
        'sh',
        -- 'swift',
        'terraform',
        'toml',
        -- 'typescript',
        -- 'typescriptreact',
        -- 'typst',
        'yaml',
    },
    root_markers = {
        '.git',
    },
    settings = {
        linters = {
            SentenceCapitalization = false,
            SpellCheck = false,
        },
    },
}
