---
gui:
  nerdFontsVersion: !!str 3
  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    cherryPickedCommitBgColor:
      - "#bb9af7"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    defaultFgColor:
      - "#c0caf5"
    inactiveBorderColor:
      - "#29a4bd"
    markedBaseCommitBgColor:
      - "#e0af68"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    optionsTextColor:
      - "#7aa2f7"
    searchingActiveBorderColor:
      - "#ff9e64"
      - bold
    selectedLineBgColor:
      - "#2e3c64"
    unstagedChangesColor:
      - "#db4b4b"
