---
arch: x86_64
autoActivate: true
cpu: 4
disk: 100
docker: {}
env: {}
forwardAgent: false
hostname: ""
kubernetes:
  enabled: true
  k3sArgs:
    - --disable=traefik
  version: v1.31.2+k3s1
memory: 4
mountInotify: false
mountType: virtiofs
mounts: []
nestedVirtualization: false
network:
  address: false
  dns: []
  dnsHosts:
    host.docker.internal: host.lima.internal
  hostAddresses: false
provision: []
rosetta: true
runtime: containerd
sshConfig: true
sshPort: 0
vmType: vz
